branch-defaults:
  default:
    environment: django-app-env
    group_suffix: null
environment-defaults:
  django-app-env:
    branch: null
    repository: null
global:
  application_name: djangosite
  branch: null
  default_ec2_keyname: prod-test-db-eb-keypair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
